version: '3.7'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-nestjs}
      POSTGRES_PASSWORD: ${DB_PASS:-nestjspw}
      POSTGRES_DB: ${DB_NAME:-nestjs_db}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${DB_PORT:-5432}:5432'

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: unless-stopped
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - '${KAFKA_PORT:-9092}:9092'
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - '${ZOOKEEPER_PORT:-2181}:2181'

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'

  rabbitmq:
    image: rabbitmq:alpine
    restart: unless-stopped
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'

volumes:
  redis:
  postgres:
